In [2]:
f'{18:02d}'

'18'

In [1]:
import sqlite3
from tables import (
    create_tables, fill_test_data_to_tables,     
    delete_collisions_by_appointment_time, 
    delete_duplicates_from_customers, 
    delete_duplicates_from_specialists, 
    show_table, show_full_schedule, 
    show_specialist_schedule, 
    insert_appointment
)
import datetime
import pandas as pd
from aiogram import types
from aiogram.utils.keyboard import InlineKeyboardBuilder

,appointment_time,customer_name,customer_phone,specialist_name,specialist_position
0,2020-05-10 15:00:00,Bob Johnson,555-5678,Emily Johnson,Nail Technician
1,2024-02-08 09:00,Alice Smith,555-1234,John Smith,Hair Stylist
2,2024-02-08 09:00,Alice Smith,555-1234,Emily Johnson,Nail Technician
3,2024-02-08 09:00:00,Alice Smith,555-1234,John Smith,Hair Stylist
4,2024-02-08 09:00:00,Alice Smith,555-1234,Emily Johnson,Nail Technician
...,...,...,...,...,...
64,2024-02-14 12:00,"['ert', '34t42t', '4igr90tig', 'h56i']",i534r5i,Emily Johnson,Nail Technician
65,2024-02-15 8:00,"['gs', 'xfjvsdfjg939534']",952,John Smith,Hair Stylist
66,2024-02-17 11:00,"['583248094', '30fj', '', 'e90jg', '9idfji9dsf...",458345345,Jessica Martinez,Massage Therapist
67,2024-02-18 8:00,"['dfk', 'dfgk', 'dfigmoig', 'sidgi', 'sdrjgi45...",3,Michael Brown,Esthetician
68,"Makeup Artist David Wilson,5 2024-02-23","['38ruwj9v', '']",345,John Smith,Hair Stylist

In [2]:
conn = sqlite3.connect('scheduler.db')

create_tables(conn)
fill_test_data_to_tables(conn)
delete_collisions_by_appointment_time(conn)
delete_duplicates_from_customers(conn)
delete_duplicates_from_specialists(conn)
show_table(conn, 'specialists')
show_full_schedule(conn)

Specialists added to specialists table. Customers added to customers table. Test records added to work_schedule table.
Collisions deleted successfully.
Duplicates deleted successfully.
Duplicates deleted successfully.

,appointment_time,customer_name,customer_phone,specialist_name,specialist_position
0,2024-02-08 09:00,Alice Smith,555-1234,John Smith,Hair Stylist
1,2024-02-08 09:00,Alice Smith,555-1234,Emily Johnson,Nail Technician
2,2024-02-08 10:00,Bob Johnson,555-5678,Emily Johnson,Nail Technician
3,2024-02-08 11:00,Charlie Brown,555-9012,Michael Brown,Esthetician
4,2024-02-08 12:00,Diana Martinez,555-3456,Jessica Martinez,Massage Therapist
5,2024-02-08 13:00,Eva Wilson,555-7890,David Wilson,Makeup Artist
6,2024-02-08 14:00,Bob Johnson,555-5678,John Smith,Hair Stylist
7,2024-02-08 15:00,Charlie Brown,555-9012,Emily Johnson,Nail Technician
8,2024-02-08 16:00,Diana Martinez,555-3456,Michael Brown,Esthetician
9,2024-02-08 17:00,Eva Wilson,555-7890,Jessica Martinez,Massage Therapist
10,2024-02-08 18:00,Alice Smith,555-1234,David Wilson,Makeup Artist
11,2024-02-09 09:00,Bob Johnson,555-5678,John Smith,Hair Stylist
12,2024-02-09 10:00,Charlie Brown,555-9012,Emily Johnson,Nail Technician
13,2024-02-09 11:00,Diana Martinez,555-3456,Michael Brown,Esthetician
14,2024-02-09 12:00,Eva Wilson,555-7890,Jessica Martinez,Massage Therapist
15,2024-02-09 13:00,Alice Smith,555-1234,David Wilson,Makeup Artist
16,2024-02-09 14:00,Charlie Brown,555-9012,John Smith,Hair Stylist
17,2024-02-09 15:00,Diana Martinez,555-3456,Emily Johnson,Nail Technician
18,2024-02-09 16:00,Eva Wilson,555-7890,Michael Brown,Esthetician
19,2024-02-09 17:00,Alice Smith,555-1234,Jessica Martinez,Massage Therapist
20,2024-02-09 18:00,Bob Johnson,555-5678,David Wilson,Makeup Artist
21,2024-02-10 09:00,Diana Martinez,555-3456,John Smith,Hair Stylist
22,2024-02-10 09:30,Eva Wilson,555-7890,Emily Johnson,Nail Technician
23,2024-02-10 10:00,Alice Smith,555-1234,Michael Brown,Esthetician
24,2024-02-10 10:30,Bob Johnson,555-5678,Jessica Martinez,Massage Therapist
25,2024-02-10 11:00,Charlie Brown,555-9012,David Wilson,Makeup Artist
26,2024-02-10 11:30,Eva Wilson,555-7890,John Smith,Hair Stylist
27,2024-02-10 12:00,Alice Smith,555-1234,Emily Johnson,Nail Technician
28,2024-02-10 12:30,Bob Johnson,555-5678,Michael Brown,Esthetician
29,2024-02-10 13:00,Charlie Brown,555-9012,Jessica Martinez,Massage Therapist
30,2024-02-10 13:30,Diana Martinez,555-3456,David Wilson,Makeup Artist